"""empty message

Revision ID: 02a58d4e737b
Revises: 
Create Date: 2018-12-25 11:06:24.890501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a58d4e737b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_to', sa.String(length=120), nullable=False),
    sa.Column('img_file', sa.String(), nullable=False),
    sa.Column('sent_by_id', sa.Integer(), nullable=False),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
