"""empty message

Revision ID: 02fa6fcaa922
Revises: 0e320b0cf128
Create Date: 2018-12-24 20:38:48.294538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fa6fcaa922'
down_revision = '0e320b0cf128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_to', sa.String(length=120), nullable=False),
    sa.Column('img_file', sa.String(), nullable=False),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
