"""empty message

Revision ID: 2eefde9cadde
Revises: 550304829d07
Create Date: 2018-12-26 09:10:23.600730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eefde9cadde'
down_revision = '550304829d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('passwd_digest', sa.String(length=200), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_to', sa.String(length=120), nullable=False),
    sa.Column('img_file', sa.String(), nullable=False),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=False),
    sa.Column('sent_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sent_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
