"""empty message

Revision ID: 550304829d07
Revises: 02a58d4e737b
Create Date: 2018-12-25 11:18:33.991929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550304829d07'
down_revision = '02a58d4e737b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sent_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sent_to_id')
    # ### end Alembic commands ###
